/** Canonical menu item schema for hybrid detail drawer (sizes, score, modifiers). */

export const demoMenuData = [
  {
    id: 'drip-coffee',
    name: 'Classic Drip Coffee',
    tagline: 'House Blend',
    description: 'Our signature smooth house blend, roasted fresh weekly.',
    category: 'coffee',
    categoryLabel: 'Coffee',
    image: '/images/espresso.png',
    basePrice: 3.5,
    score: 4.8,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: false,
    hasEspressoShot: false,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.75 },
      { label: 'Large', priceModifier: 1.5 },
    ],
    sortOrder: 1,
  },
  {
    id: 'upfordayz-mocha',
    name: 'UPFORDAYZ Mocha',
    tagline: 'Chocolate & Creamy',
    description:
      'Rich espresso folded into velvety steamed milk and dark chocolate — our house signature, finished with cocoa dust.',
    category: 'signature_drinks',
    categoryLabel: 'Signature',
    image: '/images/mocha.png',
    basePrice: 6.25,
    score: 4.9,
    hasSizes: false,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: true,
    sortOrder: 2,
  },
  {
    id: 'organic-matcha',
    name: 'Ceremonial Matcha Latte',
    tagline: 'Earthy & Vibrant',
    description: 'Pure Japanese stone-ground matcha whisked smoothly with your choice of milk.',
    category: 'lattes',
    categoryLabel: 'Lattes',
    image: '/images/latte.png',
    basePrice: 5.75,
    score: 4.7,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: false,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 1.0 },
    ],
    sortOrder: 3,
  },
  {
    id: 'demo-honey-latte',
    name: 'Honey Lavender Latte',
    tagline: 'Floral & Balanced',
    description:
      'Single-origin espresso with local honey, a whisper of lavender, and oat milk for a calm, café-quality sip.',
    category: 'signature_drinks',
    categoryLabel: 'Signature',
    image: '/images/latte.png',
    basePrice: 6.25,
    score: 4.8,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: true,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 1.0 },
    ],
    sortOrder: 4,
  },
  {
    id: 'demo-classic-latte',
    name: 'Classic Latte',
    tagline: 'Soft & Milky',
    description: 'Double shot espresso and steamed whole milk — simple, silky, and always dialed in.',
    category: 'lattes',
    categoryLabel: 'Lattes',
    image: '/images/latte.png',
    basePrice: 5.25,
    score: 4.7,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: true,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 1.0 },
    ],
    sortOrder: 5,
  },
  {
    id: 'demo-vanilla-latte',
    name: 'Vanilla Latte',
    tagline: 'Sweet & Smooth',
    description: 'Madagascar vanilla syrup meets our espresso blend for a cozy everyday favorite.',
    category: 'lattes',
    categoryLabel: 'Lattes',
    basePrice: 5.5,
    score: 4.6,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: false,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 1.0 },
    ],
    sortOrder: 6,
  },
  {
    id: 'demo-espresso',
    name: 'Double Espresso',
    tagline: 'Strong & Bold',
    description: 'Two ounces of our seasonal single-origin pull — nutty, bright, and built for purists.',
    category: 'espresso',
    categoryLabel: 'Espresso',
    image: '/images/espresso.png',
    basePrice: 3.75,
    score: 4.9,
    hasSizes: false,
    hasMilk: false,
    hasSweetness: false,
    hasEspressoShot: false,
    sortOrder: 7,
  },
  {
    id: 'demo-iced-mocha',
    name: 'Dark Mocha',
    tagline: 'Chilled & Decadent',
    description:
      'Espresso, chocolate, and cold milk over ice — the same signature mocha, built for sunny SF afternoons.',
    category: 'cold',
    categoryLabel: 'Iced & Cold',
    image: '/images/mocha.png',
    basePrice: 6.45,
    score: 4.8,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: true,
    hasEspressoShot: true,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 0.5 },
    ],
    sortOrder: 8,
  },
  {
    id: 'demo-cold-brew',
    name: 'Nitro Cold Brew',
    tagline: 'Silky & Bold',
    description: '24-hour steep, nitrogen-infused for a creamy cascade and a clean chocolate finish.',
    category: 'cold',
    categoryLabel: 'Iced & Cold',
    basePrice: 5.5,
    score: 4.9,
    hasSizes: true,
    hasMilk: true,
    hasSweetness: false,
    hasEspressoShot: false,
    sizes: [
      { label: 'Small', priceModifier: 0 },
      { label: 'Medium', priceModifier: 0.5 },
      { label: 'Large', priceModifier: 1.0 },
    ],
    sortOrder: 9,
  },
  {
    id: 'demo-croissant',
    name: 'Fresh Butter Croissant',
    tagline: 'Flaky & Golden',
    description:
      'Baked each morning with European butter — shatteringly crisp outside, tender and airy within.',
    category: 'bakery',
    categoryLabel: 'Fresh Bakery',
    basePrice: 4.5,
    score: 4.9,
    hasSizes: false,
    hasMilk: false,
    hasSweetness: false,
    hasEspressoShot: false,
    sortOrder: 10,
  },
  {
    id: 'turkey-deli-sandwich',
    name: 'Artisanal Turkey Sandwich',
    tagline: 'Savory & Fresh',
    description:
      'Smoked turkey breast, sharp white cheddar, fresh greens, and house aioli on toasted sourdough.',
    category: 'deli',
    categoryLabel: 'Deli Sandwiches',
    basePrice: 10.5,
    score: 4.6,
    hasSizes: false,
    hasMilk: false,
    hasSweetness: false,
    hasEspressoShot: false,
    sortOrder: 11,
  },
  {
    id: 'demo-caprese-panini',
    name: 'Caprese Panini',
    tagline: 'Bright & Herbaceous',
    description:
      'Fresh mozzarella, heirloom tomato, basil pesto, and balsamic glaze pressed on ciabatta.',
    category: 'deli',
    categoryLabel: 'Deli Sandwiches',
    basePrice: 10.95,
    score: 4.6,
    hasSizes: false,
    hasMilk: false,
    hasSweetness: false,
    hasEspressoShot: false,
    sortOrder: 12,
  },
];

/** Normalize demoMenuData entry for list views and cart compatibility. */
export function normalizeMenuItem(entry) {
  const sizes = entry.sizes ?? [];
  const priceFor = (index) =>
    entry.hasSizes && sizes[index]
      ? entry.basePrice + sizes[index].priceModifier
      : entry.basePrice;

  return {
    ...entry,
    rating: entry.score,
    price_small: priceFor(0),
    price_medium: entry.hasSizes ? priceFor(1) : entry.basePrice,
    price_large: entry.hasSizes ? priceFor(2) : entry.basePrice,
    image_url: entry.image || '',
    category_label: entry.categoryLabel,
    is_available: true,
    out_of_stock: false,
    doordash_item_id: entry.id,
  };
}

export function getNormalizedMenuItems() {
  return demoMenuData.map(normalizeMenuItem).sort((a, b) => a.sortOrder - b.sortOrder);
}
